# Site settings
# vim: nospell
port: 4000
output: _dist
title: Mini Jekyll
description: The smallest Jekyll website !
email: michelc@minijekyll.tk
baseurl: ""
url: "//minijekyll.tk" # the base hostname & protocol for your site
# directly drap-n-drop _site to netlify
# in production deploys section [*](https://app.netlify.com/sites/gifted-wiles-99a282/deploys?filter)
url: "//gifted-wiles-99a282.netlify.com/"
search_url: "//duckduckgo.com/?q"
googledocid: 1VfERUZ8oTEGlCT3Xn37yK1TOsYxFZuJryNNR7bhJdUM
framaid: mini_jekyll

exclude:
 - .org
 - _site
 - this.desktop
 - Gemfile
 - Gemfile.lock
 - travis.sh
